### ISSUE TITLE
Mobile compatibity

### ISSUE THREAD

**Issue by cnuis2cool** [cnuis2cool/GPSTrainings#31]
Fix the layout issue on mobile for Schedule.

![schedule_issue](https://user-images.githubusercontent.com/3716171/51584049-8c3cde00-1ef9-11e9-9482-b9ae15727f12.png)

**Comment by kashrajiv** [comment]
Working on this

**Comment by cnuis2cool** [comment]
Any update @kashrajiv ?

**Comment by kashrajiv** [comment]
Not yet cnu. Thinking of the best possible way to cover it up.

**Comment by pkkota** [comment]
@kashrajiv @cnuis2cool : looks just adding  line break before and after the **"Know more"** anchor tag will resolve the mobile compatibility issue

**Comment by kashrajiv** [comment]
@pkkota yes it fixes know more. But i am actually trying to put the whole article aligned center with the actual width same as the desktop view.
