### ISSUE TITLE
Change in Documents location

### ISSUE THREAD

**Issue by cnuis2cool** [cnuis2cool/GPSTrainings#34]
Move documents link to the new location for 2018 trainings [https://hexmet.sharepoint.com/sites/GPS-Knowledge-Sharing/Shared%20Documents/General/2018](https://hexmet.sharepoint.com/sites/GPS-Knowledge-Sharing/Shared%20Documents/General/2018)

**Comment by pkkota** [comment]
working on this

**Comment by cnuis2cool** [comment]
@kashrajiv work on this

**Comment by kashrajiv** [comment]
@cnuis2cool I modified it
