### ISSUE TITLE
Add new training

### ISSUE THREAD

**Issue by cnuis2cool** [cnuis2cool/GPSTrainings#36]
Add new training "Basic Coding Standards" by Sravani.

WebEx link: https://intergraph.webex.com/intergraph/j.php?MTID=m2be3ad34237f7f59c785706741a43bb3

Date & Time: 01st Feb, 03:30 - 03:45 pm

**Comment by kashrajiv** [comment]
Working on this

**Comment by cnuis2cool** [comment]
Added calendar file. @kashrajiv  do it asap.

**Comment by kashrajiv** [comment]
Yes
